version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: friendsofphp/php-cs-fixer
    versions:
    - 2.18.2
    - 2.18.3
    - 2.18.4
    - 2.18.5
  - dependency-name: symfony/http-kernel
    versions:
    - 4.4.19
    - 4.4.20
  - dependency-name: symfony/framework-bundle
    versions:
    - 4.4.19
  - dependency-name: symfony/options-resolver
    versions:
    - 4.4.19
  - dependency-name: symfony/serializer
    versions:
    - 4.4.19
  - dependency-name: symfony/property-access
    versions:
    - 4.4.19
  - dependency-name: symfony/http-foundation
    versions:
    - 4.4.19
  - dependency-name: phpunit/phpunit
    versions:
    - 8.5.14
  - dependency-name: doctrine/annotations
    versions:
    - 1.11.1
