services:
    _defaults:
        public: false

    super_brave_gdpr.fixed_value_anonymizer:
        class: SuperBrave\GdprBundle\Anonymize\Type\FixedValueAnonymizer
        tags:
            - { name: super_brave_gdpr.anonymizer, type: fixed }

    super_brave_gdpr.date_time_anonymizer:
        class: SuperBrave\GdprBundle\Anonymize\Type\DateTimeAnonymizer
        tags:
            - { name: super_brave_gdpr.anonymizer, type: dateTime }

    super_brave_gdpr.ip_anonymizer:
        class: SuperBrave\GdprBundle\Anonymize\Type\IpAnonymizer
        tags:
            - { name: super_brave_gdpr.anonymizer, type: ip }
